import type { CalendarEvent } from '@/types';
import { addDays, addHours, setHours, setMinutes, startOfDay } from 'date-fns';

export type EventType = 'economic' | 'fed' | 'earnings' | 'announcement';
export type EventImportance = 'high' | 'medium' | 'low';

interface EventData {
  title: string;
  type: EventType;
  importance: EventImportance;
  description: string;
  previous?: string;
  expected?: string;
  actual?: string;
  source?: string;
  relatedTickers?: string[];
  hour: number;
  minute: number;
}

const eventTemplates: Array<EventData & { dayOffset: number }> = [
  // Economic Indicators
  {
    dayOffset: 1,
    hour: 8,
    minute: 30,
    title: 'Consumer Price Index (CPI)',
    type: 'economic',
    importance: 'high',
    description: 'Monthly inflation data measuring changes in prices paid by consumers for goods and services.',
    previous: '3.1%',
    expected: '3.0%',
    actual: '2.9%',
    source: 'Bureau of Labor Statistics',
    relatedTickers: ['SPY', 'TLT', 'GLD'],
  },
  {
    dayOffset: 2,
    hour: 10,
    minute: 0,
    title: 'Unemployment Rate',
    type: 'economic',
    importance: 'high',
    description: 'Monthly employment data including non-farm payrolls and unemployment rate.',
    previous: '3.7%',
    expected: '3.7%',
    actual: '3.6%',
    source: 'Bureau of Labor Statistics',
    relatedTickers: ['SPY', 'DIA'],
  },
  {
    dayOffset: 3,
    hour: 14,
    minute: 0,
    title: 'FOMC Meeting Minutes',
    type: 'fed',
    importance: 'high',
    description: 'Federal Reserve releases detailed minutes from the latest Federal Open Market Committee meeting.',
    source: 'Federal Reserve',
    relatedTickers: ['SPY', 'TLT', 'IEF'],
  },
  {
    dayOffset: 4,
    hour: 16,
    minute: 30,
    title: 'Apple Q4 Earnings Call',
    type: 'earnings',
    importance: 'high',
    description: 'Apple Inc. reports quarterly earnings and provides guidance for the next quarter.',
    previous: '$1.52 EPS',
    expected: '$1.54 EPS',
    actual: '$1.58 EPS',
    source: 'Apple Inc.',
    relatedTickers: ['AAPL'],
  },
  {
    dayOffset: 4,
    hour: 17,
    minute: 0,
    title: 'Microsoft Q4 Earnings Call',
    type: 'earnings',
    importance: 'high',
    description: 'Microsoft Corporation reports quarterly results with focus on Azure cloud growth.',
    previous: '$2.69 EPS',
    expected: '$2.65 EPS',
    actual: '$2.72 EPS',
    source: 'Microsoft Corporation',
    relatedTickers: ['MSFT'],
  },
  {
    dayOffset: 5,
    hour: 8,
    minute: 30,
    title: 'Retail Sales Data',
    type: 'economic',
    importance: 'high',
    description: 'Monthly retail sales report showing consumer spending trends.',
    previous: '0.3%',
    expected: '0.4%',
    actual: '0.6%',
    source: 'U.S. Census Bureau',
    relatedTickers: ['XRT', 'WMT', 'TGT'],
  },
  {
    dayOffset: 6,
    hour: 9,
    minute: 0,
    title: 'Powell Speech at Economic Club',
    type: 'fed',
    importance: 'high',
    description: 'Fed Chair Jerome Powell speaks about monetary policy and economic outlook.',
    source: 'Federal Reserve',
    relatedTickers: ['SPY', 'TLT'],
  },
  {
    dayOffset: 7,
    hour: 16,
    minute: 0,
    title: 'Amazon Q4 Earnings Call',
    type: 'earnings',
    importance: 'high',
    description: 'Amazon reports quarterly earnings with AWS revenue breakdown.',
    previous: '$0.94 EPS',
    expected: '$0.98 EPS',
    source: 'Amazon.com Inc.',
    relatedTickers: ['AMZN'],
  },
  {
    dayOffset: 7,
    hour: 16,
    minute: 30,
    title: 'Meta Platforms Earnings Call',
    type: 'earnings',
    importance: 'high',
    description: 'Meta reports quarterly results with focus on advertising revenue and metaverse investments.',
    previous: '$4.71 EPS',
    expected: '$4.96 EPS',
    source: 'Meta Platforms Inc.',
    relatedTickers: ['META'],
  },
  {
    dayOffset: 8,
    hour: 8,
    minute: 30,
    title: 'Producer Price Index (PPI)',
    type: 'economic',
    importance: 'medium',
    description: 'Measures average change in selling prices received by domestic producers.',
    previous: '0.2%',
    expected: '0.3%',
    actual: '0.1%',
    source: 'Bureau of Labor Statistics',
    relatedTickers: ['SPY'],
  },
  {
    dayOffset: 9,
    hour: 10,
    minute: 0,
    title: 'Consumer Sentiment Index',
    type: 'economic',
    importance: 'medium',
    description: 'University of Michigan consumer sentiment survey results.',
    previous: '69.5',
    expected: '70.0',
    actual: '71.2',
    source: 'University of Michigan',
    relatedTickers: ['SPY', 'XLY'],
  },
  {
    dayOffset: 10,
    hour: 16,
    minute: 0,
    title: 'Alphabet Q4 Earnings Call',
    type: 'earnings',
    importance: 'high',
    description: 'Google parent company reports quarterly results with YouTube and Cloud revenue.',
    previous: '$1.55 EPS',
    expected: '$1.59 EPS',
    source: 'Alphabet Inc.',
    relatedTickers: ['GOOGL', 'GOOG'],
  },
  {
    dayOffset: 11,
    hour: 16,
    minute: 0,
    title: 'Tesla Q4 Earnings Call',
    type: 'earnings',
    importance: 'high',
    description: 'Tesla reports quarterly deliveries, revenue, and production targets.',
    previous: '$0.85 EPS',
    expected: '$0.73 EPS',
    source: 'Tesla Inc.',
    relatedTickers: ['TSLA'],
  },
  {
    dayOffset: 12,
    hour: 8,
    minute: 30,
    title: 'Housing Starts',
    type: 'economic',
    importance: 'medium',
    description: 'New residential construction data including housing starts and building permits.',
    previous: '1.56M',
    expected: '1.50M',
    actual: '1.48M',
    source: 'U.S. Census Bureau',
    relatedTickers: ['XHB', 'ITB'],
  },
  {
    dayOffset: 13,
    hour: 14,
    minute: 0,
    title: 'FOMC Meeting Decision',
    type: 'fed',
    importance: 'high',
    description: 'Federal Reserve announces interest rate decision and releases policy statement.',
    previous: '5.50%',
    expected: '5.50%',
    source: 'Federal Reserve',
    relatedTickers: ['SPY', 'TLT', 'IEF', 'DXY'],
  },
  {
    dayOffset: 13,
    hour: 14,
    minute: 30,
    title: 'Powell Press Conference',
    type: 'fed',
    importance: 'high',
    description: 'Fed Chair Jerome Powell holds press conference following FOMC decision.',
    source: 'Federal Reserve',
    relatedTickers: ['SPY', 'TLT'],
  },
  {
    dayOffset: 14,
    hour: 16,
    minute: 0,
    title: 'Netflix Q4 Earnings Call',
    type: 'earnings',
    importance: 'medium',
    description: 'Netflix reports subscriber growth and quarterly financial results.',
    previous: '$3.73 EPS',
    expected: '$2.22 EPS',
    source: 'Netflix Inc.',
    relatedTickers: ['NFLX'],
  },
  {
    dayOffset: 15,
    hour: 8,
    minute: 30,
    title: 'Initial Jobless Claims',
    type: 'economic',
    importance: 'medium',
    description: 'Weekly report on unemployment insurance claims.',
    previous: '212K',
    expected: '215K',
    actual: '210K',
    source: 'Department of Labor',
    relatedTickers: ['SPY'],
  },
  {
    dayOffset: 16,
    hour: 9,
    minute: 45,
    title: 'Manufacturing PMI',
    type: 'economic',
    importance: 'medium',
    description: 'Purchasing Managers Index measuring manufacturing sector health.',
    previous: '49.2',
    expected: '49.5',
    actual: '50.1',
    source: 'ISM',
    relatedTickers: ['XLI', 'SPY'],
  },
  {
    dayOffset: 17,
    hour: 16,
    minute: 0,
    title: 'JPMorgan Chase Earnings Call',
    type: 'earnings',
    importance: 'high',
    description: 'Major bank reports quarterly earnings with insights on lending and trading.',
    previous: '$4.37 EPS',
    expected: '$4.18 EPS',
    source: 'JPMorgan Chase & Co.',
    relatedTickers: ['JPM', 'XLF'],
  },
  {
    dayOffset: 18,
    hour: 16,
    minute: 0,
    title: 'Nvidia Earnings Call',
    type: 'earnings',
    importance: 'high',
    description: 'Nvidia reports data center and gaming revenue with AI chip demand update.',
    previous: '$5.16 EPS',
    expected: '$5.37 EPS',
    source: 'Nvidia Corporation',
    relatedTickers: ['NVDA'],
  },
  {
    dayOffset: 19,
    hour: 8,
    minute: 30,
    title: 'GDP Growth Rate',
    type: 'economic',
    importance: 'high',
    description: 'Quarterly Gross Domestic Product growth rate for the U.S. economy.',
    previous: '4.9%',
    expected: '3.3%',
    actual: '3.1%',
    source: 'Bureau of Economic Analysis',
    relatedTickers: ['SPY', 'DIA'],
  },
  {
    dayOffset: 20,
    hour: 10,
    minute: 0,
    title: 'Existing Home Sales',
    type: 'economic',
    importance: 'low',
    description: 'Monthly data on sales of previously owned homes.',
    previous: '3.96M',
    expected: '3.90M',
    actual: '3.78M',
    source: 'National Association of Realtors',
    relatedTickers: ['XHB'],
  },
  {
    dayOffset: 21,
    hour: 16,
    minute: 0,
    title: 'Disney Earnings Call',
    type: 'earnings',
    importance: 'medium',
    description: 'Disney reports streaming subscriber numbers and theme park revenue.',
    previous: '$1.03 EPS',
    expected: '$1.23 EPS',
    source: 'The Walt Disney Company',
    relatedTickers: ['DIS'],
  },
  {
    dayOffset: 22,
    hour: 11,
    minute: 0,
    title: 'Apple AI Product Launch Event',
    type: 'announcement',
    importance: 'high',
    description: 'Apple announces new AI-powered features and products.',
    source: 'Apple Inc.',
    relatedTickers: ['AAPL'],
  },
  {
    dayOffset: 23,
    hour: 9,
    minute: 0,
    title: 'Services PMI',
    type: 'economic',
    importance: 'medium',
    description: 'Purchasing Managers Index for the services sector.',
    previous: '52.6',
    expected: '53.0',
    actual: '53.4',
    source: 'ISM',
    relatedTickers: ['SPY'],
  },
  {
    dayOffset: 24,
    hour: 16,
    minute: 0,
    title: 'Walmart Earnings Call',
    type: 'earnings',
    importance: 'medium',
    description: 'Retail giant reports quarterly sales and updates full-year guidance.',
    previous: '$1.53 EPS',
    expected: '$1.52 EPS',
    source: 'Walmart Inc.',
    relatedTickers: ['WMT', 'XRT'],
  },
  {
    dayOffset: 25,
    hour: 8,
    minute: 30,
    title: 'Durable Goods Orders',
    type: 'economic',
    importance: 'low',
    description: 'Orders for manufactured goods expected to last three years or more.',
    previous: '5.4%',
    expected: '0.5%',
    actual: '0.2%',
    source: 'U.S. Census Bureau',
    relatedTickers: ['XLI'],
  },
  {
    dayOffset: 26,
    hour: 16,
    minute: 0,
    title: 'Visa Earnings Call',
    type: 'earnings',
    importance: 'medium',
    description: 'Payment processor reports transaction volume and revenue growth.',
    previous: '$2.33 EPS',
    expected: '$2.42 EPS',
    source: 'Visa Inc.',
    relatedTickers: ['V'],
  },
  {
    dayOffset: 27,
    hour: 10,
    minute: 0,
    title: 'New Home Sales',
    type: 'economic',
    importance: 'low',
    description: 'Sales of newly constructed homes in the United States.',
    previous: '679K',
    expected: '680K',
    actual: '664K',
    source: 'U.S. Census Bureau',
    relatedTickers: ['XHB', 'ITB'],
  },
  {
    dayOffset: 28,
    hour: 13,
    minute: 0,
    title: 'Microsoft Azure Expansion Announcement',
    type: 'announcement',
    importance: 'medium',
    description: 'Microsoft announces major cloud infrastructure expansion in Asia-Pacific.',
    source: 'Microsoft Corporation',
    relatedTickers: ['MSFT'],
  },
];

export function generateCalendarEvents(): CalendarEvent[] {
  const today = startOfDay(new Date());

  return eventTemplates.map((template, index) => {
    const eventDate = addDays(today, template.dayOffset);
    const startTime = setMinutes(setHours(eventDate, template.hour), template.minute);
    const endTime = addHours(startTime, 1); // Default 1-hour duration

    return {
      id: `event-${index + 1}`,
      title: template.title,
      type: template.type,
      start: startTime,
      end: endTime,
      description: template.description,
      importance: template.importance,
      previous: template.previous,
      expected: template.expected,
      actual: template.actual,
      source: template.source,
      relatedTickers: template.relatedTickers || [],
      isAlert: false,
    };
  });
}

export function getEventTypeColor(type: EventType): { bg: string; text: string; icon: string } {
  switch (type) {
    case 'economic':
      return { bg: 'bg-blue-100 dark:bg-blue-900/30', text: 'text-blue-700 dark:text-blue-300', icon: '📊' };
    case 'fed':
      return { bg: 'bg-purple-100 dark:bg-purple-900/30', text: 'text-purple-700 dark:text-purple-300', icon: '🏦' };
    case 'earnings':
      return { bg: 'bg-green-100 dark:bg-green-900/30', text: 'text-green-700 dark:text-green-300', icon: '💼' };
    case 'announcement':
      return { bg: 'bg-orange-100 dark:bg-orange-900/30', text: 'text-orange-700 dark:text-orange-300', icon: '📢' };
    default:
      return { bg: 'bg-gray-100 dark:bg-gray-900/30', text: 'text-gray-700 dark:text-gray-300', icon: '📅' };
  }
}

export function getImportanceBadge(importance: EventImportance): { color: string; label: string } {
  switch (importance) {
    case 'high':
      return { color: 'bg-negative-100 dark:bg-negative-900/30 text-negative-700 dark:text-negative-300', label: '🔴 High' };
    case 'medium':
      return { color: 'bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-300', label: '🟡 Medium' };
    case 'low':
      return { color: 'bg-gray-100 dark:bg-gray-900/30 text-gray-600 dark:text-gray-400', label: '⚪ Low' };
    default:
      return { color: 'bg-gray-100 dark:bg-gray-900/30 text-gray-600 dark:text-gray-400', label: '⚪ Low' };
  }
}
